remote_theme: just-the-docs/just-the-docs
color_scheme: dark
site_favicon: favicon.ico
title: Chris Campbell
description: Learning stuff and making things.
show_downloads: false
github:
  is_project_page: false