remote_theme: just-the-docs/just-the-docs
color_scheme: dark
favicon_ico: /assets/images/favicon.ico
logo: /assets/images/logo-color.png
title: NerdWire Blog
description: Learning stuff and making things.
show_downloads: false
github:
  is_project_page: false
nav_external_links:
  - title: Printables
    url: https://www.printables.com/@ccmpbll
    hide_icon: false
  - title: Github
    url: https://github.com/ccmpbll
    hide_icon: false
  - title: What I'm Reading
    url: https://www.goodreads.com/user/show/163287154-chris-campbell
    hide_icon: false